#application package base
domain = "com.tezov"
merge = "${file://./tezov.catalog.dependencies.yaml}"

#Configuration plugin application
[plugins_apply_to]
app = [
  "${plugins.application}",
  "${plugins.kotlin}",
  "${plugins.tezov_project_config}"
]
lib = [
  "${plugins.library}",
  "${plugins.kotlin}",
  "${plugins.tezov_project_config}"
]